[package]
name = "rust_graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.27.0"

# [profile.release]
# debug = true    # or 1 for smaller symbols
# strip = false   # Keep symbols in the binary
